#!/bin/bash
###########################
##  auto update script   ##
cd /usr/src/the_commander ;
git pull ;
###########################
touch /tmp/testscript ;
echo "\nLast run: \n">> /tmp/the_commander.tmp
date >> /tmp/the_commander.tmp ;

