#!/bin/bash
###########################
##  auto update script   ##
cd /usr/src/the_commander ;
git fetch --all ;
git reset --hard ;
git pull ;
###########################
##         tests         ##
echo "Last run:"> /tmp/the_commander.tmp
date >> /tmp/the_commander.tmp ;
###########################

